"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { ErrorPanel, LoadingPanel, Notice } from "@/components/animals/animal-ui";
import { apiClient } from "@/lib/api-client";
import { type Dictionary, type Locale } from "@/lib/i18n";
import { useFarmerSession } from "@/lib/use-farmer-session";
import type { OwnerMarketplaceListing, UpdateMarketplaceListingInput } from "@/types/listing";
import { apiError } from "@/components/marketplace/common";

type Props = { locale: Locale; dictionary: Dictionary; listingId: string };
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-secondary">{label}<span className="mt-1 block">{children}</span>{error ? <p className="mt-1 text-xs text-error">{error}</p> : null}</label>; }
export function EditListingScreen({ locale, dictionary, listingId }: Props) {
  const t = dictionary.marketplace, router = useRouter(), { state: session, token, handleApiError } = useFarmerSession(locale); const [listing, setListing] = useState<OwnerMarketplaceListing | null>(null), [state, setState] = useState<"loading" | "ready" | "error">("loading"), [error, setError] = useState(""), [success, setSuccess] = useState(""); const form = useForm<UpdateMarketplaceListingInput>();
  const load = useCallback(async () => { if (!token) return; setState("loading"); try { const data = await apiClient.getMyMarketplaceListing(token, listingId); setListing(data); form.reset({ title: data.title, description: data.description ?? "", price_mad: data.price_mad, contact_phone: data.contact_phone, contact_whatsapp: data.contact_whatsapp ?? "" }); setState("ready"); } catch (cause) { if (!handleApiError(cause)) { setError(apiError(cause, t.loadError)); setState("error"); } } }, [form, handleApiError, listingId, t.loadError, token]); useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const submit = form.handleSubmit(async (values) => { if (!token || !listing) return; try { await apiClient.updateMarketplaceListing(token, listing.id, { ...values, description: values.description || null, contact_whatsapp: values.contact_whatsapp || null }); setSuccess(t.updateSuccess); } catch (cause) { setError(apiError(cause, t.actionError)); } });
  if (session === "loading" || state === "loading") return <LoadingPanel label={t.loading} />; if (session === "forbidden") return <ErrorPanel title={t.farmerOnlyTitle} message={t.farmerOnlyDescription} />; if (state === "error" || !listing) return <ErrorPanel title={error === "Listing not found" ? t.notFound : dictionary.common.error} message={error} retry={load} retryLabel={dictionary.common.retry} />;
  const editable = listing.status === "active" && new Date(listing.expires_at) > new Date();
  return <div className="mx-auto max-w-3xl space-y-6"><h1 className="text-3xl font-black text-primary">{t.edit}</h1>{!editable ? <Notice message={t.editUnavailable} error /> : null}<form onSubmit={submit} className="space-y-5 rounded-2xl border border-secondary-container bg-white p-5 shadow-sm"><Field label={t.titleLabel} error={form.formState.errors.title?.message}><input disabled={!editable} {...form.register("title", { required: t.required, maxLength: { value: 255, message: t.validationError } })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3 disabled:bg-surface-container" /></Field><Field label={t.description}><textarea disabled={!editable} {...form.register("description", { maxLength: 4000 })} className="min-h-28 w-full rounded-lg border border-secondary-container p-3 disabled:bg-surface-container" /></Field><Field label={t.price} error={form.formState.errors.price_mad?.message}><input disabled={!editable} type="number" step="0.01" {...form.register("price_mad", { required: t.required, validate: (value) => Number(value) > 0 || t.invalidPrice })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3 disabled:bg-surface-container" /></Field><Field label={t.contactPhone} error={form.formState.errors.contact_phone?.message}><input disabled={!editable} {...form.register("contact_phone", { required: t.required, minLength: { value: 6, message: t.validationError }, maxLength: { value: 32, message: t.validationError } })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3 disabled:bg-surface-container" /></Field><Field label={t.contactWhatsapp}><input disabled={!editable} {...form.register("contact_whatsapp", { maxLength: 32 })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3 disabled:bg-surface-container" /></Field>{error ? <Notice message={error} error /> : null}{success ? <Notice message={success} /> : null}{editable ? <button disabled={form.formState.isSubmitting} className="min-h-12 rounded-xl bg-primary px-5 text-sm font-bold text-on-primary">{form.formState.isSubmitting ? t.updating : t.update}</button> : <button type="button" onClick={() => router.push(`/${locale}/marketplace/my-listings`)} className="min-h-11 rounded-xl border border-secondary-container px-4 text-sm font-bold">{t.myListings}</button>}</form></div>;
}
