"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { ConfirmationDialog, EmptyPanel, ErrorPanel, LoadingPanel, Notice } from "@/components/animals/animal-ui";
import { apiClient } from "@/lib/api-client";
import { type Dictionary, type Locale } from "@/lib/i18n";
import { useFarmerSession } from "@/lib/use-farmer-session";
import type { Animal, AnimalPhoto } from "@/types/animal";
import type { CreateMarketplaceListingInput, ListingStatus, OwnerMarketplaceListing } from "@/types/listing";
import { apiError, formatDate, formatMoney, ListingImage, Paging, Status } from "@/components/marketplace/common";

type Props = { locale: Locale; dictionary: Dictionary };
const statuses: ListingStatus[] = ["active", "expired", "sold", "suspended", "draft"];

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-secondary">{label}<span className="mt-1 block">{children}</span>{error ? <p className="mt-1 text-xs text-error">{error}</p> : null}</label>; }
function FarmerGate({ state, dictionary }: { state: "loading" | "ready" | "forbidden"; dictionary: Dictionary }) { const t = dictionary.marketplace; if (state === "loading") return <LoadingPanel label={t.loading} />; if (state === "forbidden") return <ErrorPanel title={t.farmerOnlyTitle} message={t.farmerOnlyDescription} />; return null; }

export function SellListingScreen({ locale, dictionary }: Props) {
  const t = dictionary.marketplace, router = useRouter(), { state: session, token, handleApiError } = useFarmerSession(locale);
  const [animals, setAnimals] = useState<Array<Animal & { photos: AnimalPhoto[] }>>([]), [state, setState] = useState<"loading" | "ready" | "error">("loading"), [error, setError] = useState("");
  const form = useForm<CreateMarketplaceListingInput>({ defaultValues: { title: "", description: "", price_mad: "", contact_phone: "", contact_whatsapp: "" } });
  const load = useCallback(async () => { if (!token) return; setState("loading"); try { const raw = await apiClient.listAnimals(token); setAnimals(await Promise.all(raw.map(async (animal) => ({ ...animal, photos: await apiClient.listAnimalPhotos(token, animal.id) })))); setState("ready"); } catch (cause) { if (!handleApiError(cause)) { setError(apiError(cause, t.loadError)); setState("error"); } } }, [handleApiError, t.loadError, token]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]); const eligible = animals.filter((animal) => !["sold", "dead", "listed"].includes(animal.ownership_status) && animal.photos.length > 0);
  const submit = form.handleSubmit(async (values) => { if (!token) return; try { const listing = await apiClient.createMarketplaceListing(token, { ...values, description: values.description || null, contact_whatsapp: values.contact_whatsapp || null }); router.push(`/${locale}/marketplace/my-listings/${listing.id}/edit`); } catch (cause) { if (!handleApiError(cause)) setError(apiError(cause, t.actionError)); } });
  if (session !== "ready") return <FarmerGate state={session} dictionary={dictionary} />; if (state === "loading") return <LoadingPanel label={t.loading} />; if (state === "error") return <ErrorPanel title={dictionary.common.error} message={error} retry={load} retryLabel={dictionary.common.retry} />;
  return <div className="mx-auto max-w-3xl space-y-6"><header><h1 className="text-3xl font-black text-primary">{t.createTitle}</h1><p className="mt-2 text-sm text-on-surface-variant">{t.createSubtitle}</p></header>{eligible.length === 0 ? <EmptyPanel title={t.noEligible} description={t.noEligibleDescription} action={<Link href={`/${locale}/animals`} className="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-on-primary">{t.managePhotos}</Link>} /> : <form onSubmit={submit} className="space-y-5 rounded-2xl border border-secondary-container bg-white p-5 shadow-sm"><Field label={t.chooseAnimal} error={form.formState.errors.animal_id?.message}><select {...form.register("animal_id", { required: t.required })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3"><option value="">—</option>{eligible.map((animal) => <option key={animal.id} value={animal.id}>{animal.species} · {animal.breed ?? animal.id.slice(0, 8)} · {animal.sale_readiness}</option>)}</select></Field><Field label={t.titleLabel} error={form.formState.errors.title?.message}><input {...form.register("title", { required: t.required, maxLength: { value: 255, message: t.validationError } })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3" /></Field><Field label={t.description} error={form.formState.errors.description?.message}><textarea {...form.register("description", { maxLength: { value: 4000, message: t.validationError } })} className="min-h-28 w-full rounded-lg border border-secondary-container p-3" /></Field><Field label={t.price} error={form.formState.errors.price_mad?.message}><input type="number" step="0.01" {...form.register("price_mad", { required: t.required, validate: (value) => Number(value) > 0 || t.invalidPrice })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3" /></Field><Field label={t.contactPhone} error={form.formState.errors.contact_phone?.message}><input {...form.register("contact_phone", { required: t.required, minLength: { value: 6, message: t.validationError }, maxLength: { value: 32, message: t.validationError } })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3" /></Field><Field label={t.contactWhatsapp}><input {...form.register("contact_whatsapp", { maxLength: 32 })} className="min-h-11 w-full rounded-lg border border-secondary-container px-3" /></Field>{error ? <Notice message={error} error /> : null}<button disabled={form.formState.isSubmitting} className="min-h-12 rounded-xl bg-primary px-5 text-sm font-bold text-on-primary">{form.formState.isSubmitting ? t.creating : t.create}</button></form>}</div>;
}

export function MyListingsScreen({ locale, dictionary }: Props) {
  const t = dictionary.marketplace, { state: session, token, handleApiError } = useFarmerSession(locale); const [data, setData] = useState<{ items: OwnerMarketplaceListing[]; page: number; pages: number } | null>(null), [state, setState] = useState<"loading" | "ready" | "error">("loading"), [status, setStatus] = useState<ListingStatus | undefined>(), [error, setError] = useState(""), [action, setAction] = useState<{ id: string; kind: "sold" | "renew" } | null>(null), [notice, setNotice] = useState("");
  const load = useCallback(async (page = 1) => { if (!token) return; setState("loading"); try { setData(await apiClient.getMyMarketplaceListings(token, { status, page, page_size: 12 })); setState("ready"); } catch (cause) { if (!handleApiError(cause)) { setError(apiError(cause, t.loadError)); setState("error"); } } }, [handleApiError, status, t.loadError, token]); useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const mutate = async () => { if (!token || !action) return; try { if (action.kind === "sold") await apiClient.markMarketplaceListingSold(token, action.id); else await apiClient.renewMarketplaceListing(token, action.id); setNotice(action.kind === "sold" ? t.soldSuccess : t.renewSuccess); setAction(null); await load(data?.page); } catch (cause) { setError(apiError(cause, t.actionError)); setAction(null); } };
  if (session !== "ready") return <FarmerGate state={session} dictionary={dictionary} />; if (state === "loading") return <LoadingPanel label={t.loading} />; if (state === "error") return <ErrorPanel title={dictionary.common.error} message={error} retry={load} retryLabel={dictionary.common.retry} />;
  return <div className="space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><h1 className="text-3xl font-black text-primary">{t.ownerTitle}</h1><Link href={`/${locale}/marketplace/sell`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-primary px-5 py-3 text-sm font-bold text-on-primary">{t.create}</Link></header><nav aria-label={t.status} className="flex gap-2 overflow-x-auto"><button onClick={() => setStatus(undefined)} className="min-h-10 rounded-xl border border-secondary-container px-4 text-sm font-bold">{t.all}</button>{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className="min-h-10 rounded-xl border border-secondary-container px-4 text-sm font-bold">{t[item]}</button>)}</nav>{notice ? <Notice message={notice} /> : null}{data?.items.length === 0 ? <EmptyPanel title={t.emptyTitle} description={t.emptyDescription} /> : <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data?.items.map((listing) => <OwnerCard key={listing.id} listing={listing} locale={locale} dictionary={dictionary} open={(kind) => setAction({ id: listing.id, kind })} />)}</section>}{data ? <Paging page={data.page} pages={data.pages} onPage={(page) => void load(page)} dictionary={dictionary} /> : null}<ConfirmationDialog open={!!action} title={action?.kind === "sold" ? t.soldConfirmTitle : t.renewConfirmTitle} description={action?.kind === "sold" ? t.soldConfirmDescription : t.renewConfirmDescription} cancelLabel={t.cancel} confirmLabel={t.confirm} pendingLabel={t.processing} pending={false} onCancel={() => setAction(null)} onConfirm={() => void mutate()} /></div>;
}
function OwnerCard({ listing, locale, dictionary, open }: { listing: OwnerMarketplaceListing; locale: Locale; dictionary: Dictionary; open: (kind: "sold" | "renew") => void }) { const t = dictionary.marketplace; return <article className="rounded-2xl border border-secondary-container bg-white p-4 shadow-sm"><div className="flex gap-3"><ListingImage listing={listing} alt={listing.title} className="size-20 rounded-xl" /><div className="min-w-0 flex-1"><h2 className="truncate font-black text-primary">{listing.title}</h2><p className="mt-1 font-bold text-primary">{formatMoney(listing.price_mad, locale)}</p><Status value={listing.status} dictionary={dictionary} /></div></div><p className="mt-3 text-xs text-on-surface-variant">{t.expires}: {formatDate(listing.expires_at, locale)} · {t.trust}: {listing.trust_score}/100</p><div className="mt-4 flex flex-wrap gap-2">{listing.status === "active" ? <><Link href={`/${locale}/marketplace/my-listings/${listing.id}/edit`} className="rounded-lg border border-primary px-3 py-2 text-xs font-bold text-primary">{t.edit}</Link><Link href={`/${locale}/marketplace/${listing.id}`} className="rounded-lg border border-secondary-container px-3 py-2 text-xs font-bold">{t.viewPublic}</Link><button onClick={() => open("sold")} className="rounded-lg bg-error px-3 py-2 text-xs font-bold text-white">{t.markSold}</button></> : null}{listing.status === "expired" ? <button onClick={() => open("renew")} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-on-primary">{t.renew}</button> : null}</div></article>; }
